stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: "-B -Dmaven.test.skip=false"

cache:
  paths:
    - .m2/repository

maven-build:
  image: maven:3.9.6-eclipse-temurin-17
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - target/demo-0.0.1-SNAPSHOT.jar
    expire_in: 1 week

maven-test:
  image: maven:3.9.6-eclipse-temurin-17
  stage: test
  script:
    - mvn -B test
  needs:
    - maven-build
